.circleci/config.yml, FinanceServicesApi/serverless.yml, terraform/production/main.tf, terraform/staging/main.tf
=> build-test-run enabled and some changes in terraform as well

FinanceServicesApi/serverless.yml
=> Authentication management

FinanceServicesApi/serverless.yml
=> VPC changes

FinanceServicesApi/Startup.cs
=> Temporary disable the Authorization

FinanceServicesApi/FinanceServicesApi.csproj, FinanceServicesApi/Properties/launchSettings.json, FinanceServicesApi/Startup.cs, FinanceServicesApi/V1/Infrastructure/HousingData.cs
=> updating the authorization nuget package

FinanceServicesApi/Startup.cs, FinanceServicesApi/V1/Infrastructure/GetAssetEnvironmentVariables.cs, FinanceServicesApi/V1/Infrastructure/GetContactEnvironmentVariables.cs, FinanceServicesApi/V1/Infrastructure/GetPersonEnvironmentVariables.cs, FinanceServicesApi/V1/Infrastructure/GetTenureEnvironmentVariables.cs, FinanceServicesApi/serverless.yml
[Resident-Property](https://app.clickup.com/t/1kcgrhd)
preparing some data for property and resident screens (tenants and leaseholders), this PR is for deploying to the staging environment
calling housing APIs such as
1. Person API
2. Tenure information API
3. Asset information
fetching finance data directly from dynamoDB such as
1. Accounts table
2. Charges table
3. Transactions table
=> Local token variable replaced by Input Authorization token

CODEOWNERS, FinanceServicesApi/serverless.yml
- Remove token references and update url parameters
- To clear up config and ensure API sends requests to the correct services.
=> Configuration Updates

FinanceServicesApi/V1/Boundary/Responses/PropertySummary/PropertySummaryResponse.cs, FinanceServicesApi/V1/Controllers/DummyController.cs, FinanceServicesApi/V1/Infrastructure/Enums/EAccountStatus.cs
=> Temporary dummy data generator

FinanceServicesApi/V1/Controllers/DummyController.cs
=> Temporary dummy data - fixing bug

FinanceServicesApi/V1/Controllers/DummyController.cs, FinanceServicesApi/V1/Infrastructure/CustomeHttpClient.cs
=> Timeout increased

FinanceServicesApi/V1/Controllers/DummyController.cs
=> fixing format & retrieving dummy data

FinanceServicesApi/V1/Controllers/DummyController.cs, FinanceServicesApi/V1/Infrastructure/AssetUrlGenerator.cs
=> asset url fixed & fixing format

FinanceServicesApi/V1/Controllers/DummyController.cs, FinanceServicesApi/serverless.yml
=> fixing dummy data generator

FinanceServicesApi/V1/Controllers/DummyController.cs, FinanceServicesApi/V1/Domain/AccountModels/AccountBalanceUpdateModel.cs
=> Account update dummy data

FinanceServicesApi/V1/Controllers/DummyController.cs, FinanceServicesApi/V1/Domain/AccountModels/AccountBalanceUpdateModel.cs, FinanceServicesApi/V1/Domain/AccountModels/AccountPatchModel.cs
=> Some business bug fixed

FinanceServicesApi/V1/Controllers/DummyController.cs
=> handling nullreference exception

FinanceServicesApi/V1/Controllers/PropertySummaryController.cs, FinanceServicesApi/V1/Factories/ResponseFactory.cs
=> Some changes in property detail's charges

FinanceServicesApi/V1/Controllers/PropertySummaryController.cs
=> PersonId removed in PropertySummary's input parameters

FinanceServicesApi/V1/Controllers/PropertySummaryController.cs, FinanceServicesApi/V1/Controllers/ResidentSummaryController.cs
=> PersonId removed from the input parameters

FinanceServicesApi/V1/Controllers/ResidentSummaryController.cs
=> PersonId removed from input of endpoints

FinanceServicesApi.Tests/V1/Controllers/BaseControllerTests.cs
=> usage correction

FinanceServicesApi.Tests/V1/Gateways/ContactDetailsGatewayTests.cs
=> unit testing bug fixed

FinanceServicesApi/Startup.cs, FinanceServicesApi/serverless.yml
Fixed Google Group Authorization
Fixed Google Group Authorization
Fixed Google Group Authorization
=> Fixed Google Group Authorization

FinanceServicesApi/V1/Controllers/LeaseholdAssetSearchController.cs, FinanceServicesApi/V1/Gateways/HousingSearchGateway.cs, FinanceServicesApi/V1/UseCase/GetLeaseholdAssetsListUseCase.cs
Fixed typo
Fixed typo
Fixed typo
- [true ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [true  ] Added tests to cover all new production code
- [ true ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ true ] Checked all code for possible refactoring
- [ true ] Code pipeline builds correctly
=> Fixed typo

FinanceServicesApi/V1/Boundary/Responses/PropertySummary/PropertySearchResponse.cs, FinanceServicesApi/V1/UseCase/GetLeaseholdAssetsListUseCase.cs
Added Tenure Id and ChargeId in Leasehold Search Response
Added Tenure Id and ChargeId in Leasehold Search Response
Added Tenure Id and ChargeId in Leasehold Search Response
- [true ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [true  ] Added tests to cover all new production code
- [true  ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [true  ] Checked all code for possible refactoring
- [true  ] Code …
=> Added Tenure Id and ChargeId in Leasehold Search Response

FinanceServicesApi/V1/Infrastructure/Enums/ETargetType.cs
Added all target types
Added all target types
Added all target types
- [true ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [true  ] Added tests to cover all new production code
- [true  ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [true  ] Checked all code for possible refactoring
- [ true ] Code pipeline builds correctly
=> Added all target types

FinanceServicesApi/V1/Infrastructure/QueryResponseExtension.cs
Added null check
Added null check
Added null check
- [ true] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ true] Added tests to cover all new production code
- [true ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [true ] Checked all code for possible refactoring
- [true ] Code pipeline builds correctly
=> Added null check

FinanceServicesApi/V1/Infrastructure/QueryResponseExtension.cs
Commenting enum
Commenting enum
Commenting enum
=> Commenting enum

FinanceServicesApi/V1/Infrastructure/QueryResponseExtension.cs
=> Unit testing

FinanceServicesApi/V1/Infrastructure/QueryResponseExtension.cs
Added Charge Type in Charges Conversion
Added Charge Type in Charges Conversion
Added Charge Type in Charges Conversion
- [true ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [true ] Added tests to cover all new production code
- [ true] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ true] Checked all code for possible refactoring
- [ true] Code pipeline builds correctly
Are there any next steps that need to …
=> Added Charge Type in Charges Conversion

FinanceServicesApi.Tests/V1/Gateways/ChargesGatewayTests.cs, FinanceServicesApi/Startup.cs, FinanceServicesApi/V1/Controllers/ResidentSummaryController.cs, FinanceServicesApi/V1/Gateways/ChargesGateway.cs, FinanceServicesApi/V1/Infrastructure/Environments/GetChargesEnvironmentVariables.cs, FinanceServicesApi/V1/Infrastructure/Environments/GetTenureEnvironmentVariables.cs, FinanceServicesApi/V1/Infrastructure/HousingData.cs, FinanceServicesApi/V1/Infrastructure/UrlGenerators/AssetUrlGenerator.cs, FinanceServicesApi/V1/Infrastructure/UrlGenerators/ChargesUrlGenerator.cs, FinanceServicesApi/V1/Infrastructure/UrlGenerators/ContactDetailUrlGenerator.cs, FinanceServicesApi/V1/Infrastructure/UrlGenerators/PersonUrlGenerator.cs, FinanceServicesApi/V1/Infrastructure/UrlGenerators/TenureUrlGenerator.cs
TBA
As a service level API I want to use Http requests to access third-party APIs
Change ChargesGateway to use HousingData helper class
=> Add logic to use HousingData helper class to get charges

FinanceServicesApi/V1/Infrastructure/Enums/EChargeType.cs
=> Bug fiixng

FinanceServicesApi/V1/Infrastructure/DetailedChargeForYear.cs
There build error because of nullable field in charge model.
Property ChargeSubGroup became nullable in DetailedChargeForYear model.
=> Fixed build error

FinanceServicesApi/V1/Boundary/Responses/PropertySummary/PropertySearchResponse.cs, FinanceServicesApi/V1/Infrastructure/DetailedChargeForYear.cs, FinanceServicesApi/V1/UseCase/GetLeaseholdAssetsListUseCase.cs
=> Revoking the inverse Merg

FinanceServicesApi.Tests/V1/Gateways/AccountGatewayTests.cs, FinanceServicesApi/Startup.cs, FinanceServicesApi/V1/Boundary/Responses/GetAccountListResponse.cs, FinanceServicesApi/V1/Factories/ResponseFactory.cs, FinanceServicesApi/V1/Gateways/AccountGateway.cs, FinanceServicesApi/V1/Gateways/Interfaces/IAccountGateway.cs, FinanceServicesApi/V1/Infrastructure/Enums/ERentGroupType.cs, FinanceServicesApi/V1/Infrastructure/Environments/GetAccountsEnvironmentVariables.cs, FinanceServicesApi/V1/Infrastructure/HousingData.cs, FinanceServicesApi/V1/Infrastructure/UrlGenerators/AccountsUrlGenerator.cs, FinanceServicesApi/V1/UseCase/GetAccountByTargetIdUseCase.cs, FinanceServicesApi/V1/UseCase/Interfaces/IGetAccountByTargetIdUseCase.cs
=> Fixing formula

FinanceServicesApi/V1/Controllers/PropertySummaryController.cs
=> Person id fetched from housholdmember

FinanceServicesApi/V1/Controllers/PropertySummaryController.cs
=> IsResponsible person selected as person from houshold member

FinanceServicesApi/V1/Factories/ResponseFactory.cs
=> Extra charges picked the last year charges list

FinanceServicesApi/V1/Controllers/PropertySummaryController.cs
=> Message correction

FinanceServicesApi/V1/Factories/ResponseFactory.cs
=> financial year amendment
